# Generated by Django 6.0.3 on 2026-03-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assinatura_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status da Assinatura'),
        ),
        migrations.AddField(
            model_name='user',
            name='plano',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Plano'),
        ),
        migrations.AddField(
            model_name='user',
            name='proxima_cobranca',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Próxima Cobrança'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subscription ID Kirvano'),
        ),
        migrations.AddField(
            model_name='user',
            name='tem_plano',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
    ]
