# Generated by Django 6.0.3 on 2026-03-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='categoria',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='data_transacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Transação'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_financial',
            field=models.BooleanField(default=False, verbose_name='É Transação Financeira?'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status de Pagamento'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tipo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor'),
        ),
    ]
