# Generated by Django 6.0.3 on 2026-03-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KirvanoWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, max_length=100, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log Kirvano Webhook',
                'verbose_name_plural': 'Logs Kirvano Webhook',
                'db_table': 'kirvano_webhook_logs',
            },
        ),
    ]
