# Generated by Django 6.0.3 on 2026-03-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('TEXT', 'Texto'), ('AUDIO', 'Áudio'), ('IMAGE', 'Imagem')], default='TEXT', max_length=10)),
                ('direction', models.CharField(choices=[('INBOUND', 'Recebida'), ('OUTBOUND', 'Enviada')], default='INBOUND', max_length=10)),
                ('content', models.TextField()),
                ('media_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'db_table': 'bot_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
